#-------------------------------
# General Site Settings
baseurl: "" # /krusplanteria the subpath of your site, e.g. /blog
url: "https://www.krusplanteria.com" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page/:num"


exclude:
  - _data/images.yml

#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projectes:
    output: true
    permalink: /projectes/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "projectes"
    values:
      layout: "projecte"

sass:
  sass_dir: _sass
  style: compressed